# Generated by Django 5.1.7 on 2025-03-20 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('chain', models.CharField(max_length=50)),
                ('balance_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('address', 'chain')},
            },
        ),
        migrations.CreateModel(
            name='WalletUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet')),
            ],
            options={
                'unique_together': {('user', 'wallet')},
            },
        ),
    ]
